### ISSUE TITLE
Working in Plone 5?

### ISSUE THREAD

**Issue by richardtc** [collective/collective.portletpage#11]
Hi,
I can install but receive error in Plone 5.0.2 after adding and saving portlet page:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module 42fd71aad5f48a9a2d904134b79a9f13.py, line 484, in render
  Module 71edb95f573de1ebe1a615137ba7ae31.py, line 1223, in render_master
  Module 71edb95f573de1ebe1a615137ba7ae31.py, line 420, in render_content
  Module 42fd71aad5f48a9a2d904134b79a9f13.py, line 472, in __fill_content_core
  Module 42fd71aad5f48a9a2d904134b79a9f13.py, line 95, in render_content_core
  Module chameleon.utils, line 404, in __getitem__
NameError: text

 - Expression: "text"
 - Filename:   ... -py2.7.egg/collective/portletpage/browser/two-columns.pt
 - Location:   (line 18: col 22)
 - Source:     <div tal:condition="text" metal:use-macro="python:context.wi ...
                                   ^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7fdaa2639d50>
               views: <ViewMapper - at 0x7fdaa2639ad0>
               modules: <instance - at 0x7fdaacd17878>
               args: <tuple - at 0x7fdab4711050>
               here: <ImplicitAcquisitionWrapper portlet-papge-test at 0x7fdaa5772280>
               user: <ImplicitAcquisitionWrapper - at 0x7fdaa556c550>
               nothing: <NoneType - at 0x920190>
               container: <ImplicitAcquisitionWrapper portlet-papge-test at 0x7fdaa5772280>
               request: <instance - at 0x7fdaa24ad320>
               wrapped_repeat: <SafeMapping - at 0x7fdaa1ed3e68>
               traverse_subpath: <list - at 0x7fdaa25d9dd0>
               default: <object - at 0x7fdab4630500>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper portlet-papge-test at 0x7fdaa5772280>
               view: <TwoColumns two-columns at 0x7fdaa221cdd0>
               translate: <function translate at 0x7fdaa222b488>
               root: <ImplicitAcquisitionWrapper Zope at 0x7fdaa6881050>
               options: {...} (0)
               target_language: <NoneType - at 0x920190>

**Comment by keul** [comment]
@richardtc have you tested the latest unreleased master or the 1.2.2 version?
@tomgross did Plone 5 compatibility work but we never released a new version.

**Comment by richardtc** [comment]
Yesterday I tied 1.2.2 which gave me the above error. 

I also tested the master version -  I can add a portlet page item in Plone but get the following error after trying to save:

Module zope.component.registry, line 321, in subscribers
Module zope.interface.adapter, line 585, in subscribers
Module zope.component.event, line 32, in objectEventNotify
Module zope.component._api, line 136, in subscribers
Module zope.component.registry, line 321, in subscribers
Module zope.interface.adapter, line 585, in subscribers
Module archetypes.multilingual.subscriber, line 22, in __call__
Module archetypes.multilingual.subscriber, line 33, in handle_modified
TypeError: ('Could not adapt', <PortletPage at /Plone/en/portlet-page-test2>, <InterfaceClass plone.app.multilingual.interfaces.ILanguageIndependentFieldsManager>)

**Comment by keul** [comment]
@richardtc mmhhh... this issue seems related to the presence of archetypes.multilingual (which is full of bugs in my experience).
I hope to find time to investigate this.

**Comment by cekk** [comment]
@richardtc your problem is for Plone 4 or Plone 5?
If it's for plone 4, i think that we can move to #12 or create a new issue.

Plone 5 problems (chameleon) are solved.

**Comment by cekk** [comment]
@tomgross @keul do you think we can release a new version of this package?
I need the fixes made for chameleon :)

**Comment by keul** [comment]
The @richardtc issue was on Plone 5 but never find time to investigate it.
Apart of that, the add-on seems to be working on Plone 5, also with p.a.multilingua and archetypes.multilingual installed, **but** you get an error trying to translate it:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.ATContentTypes.tool.factory, line 493, in **call**
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFFormController.FSControllerPageTemplate, line 91, in **call**
  Module Products.CMFFormController.BaseControllerPageTemplate, line 32, in _call
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 237, in _exec
  Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
  Module Products.PageTemplates.PageTemplate, line 87, in pt_render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 98, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 261, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module d0e2546378ac57e4f5025b1079269dfd.py, line 1757, in render
  Module d0e2546378ac57e4f5025b1079269dfd.py, line 1574, in render_master
  Module 155aee19a020fb6455f61f3f27483632.py, line 1223, in render_master
  Module 155aee19a020fb6455f61f3f27483632.py, line 458, in render_content
  Module d0e2546378ac57e4f5025b1079269dfd.py, line 1562, in **fill_main
  Module d0e2546378ac57e4f5025b1079269dfd.py, line 599, in render_main
  Module five.pt.expressions, line 141, in __call**
  Module Products.PageTemplates.Expressions, line 117, in render
  Module plone.app.multilingual.browser.utils, line 154, in current_language_name
AttributeError: 'NoneType' object has no attribute 'get'

```
 - Expression: "pamutils/current_language_name"
 - Filename:   ... tilingual/skins/archetypesmultilingual/at_babel_edit.cpt
 - Location:   (line 129: col 73)
 - Source:     ... " tal:content="pamutils/current_language_name" tal:omit-tag= ...
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ImplicitAcquisitionWrapper at_babel_edit at 0x115ac2a00>
               modules: <instance - at 0x112752f38>
               here: <ImplicitAcquisitionWrapper portlet_page.2016-07-15.2674907904 at 0x115ac2cd0>
               user: <ImplicitAcquisitionWrapper - at 0x115969370>
               nothing: <NoneType - at 0x10fa3ef98>
               container: <ImplicitAcquisitionWrapper Plone at 0x116063be0>
               default: <object - at 0x10fb80c00>
               request: <instance - at 0x11894ae18>
               wrapped_repeat: <SafeMapping - at 0x118b82838>
               traverse_subpath: <list - at 0x1183ed6c8>
               loop: {...} (2)
               context: <ImplicitAcquisitionWrapper portlet_page.2016-07-15.2674907904 at 0x115ac2cd0>
               translate: <function translate at 0x11705d500>
               root: <ImplicitAcquisitionWrapper Zope at 0x1153771e0>
               options: {...} (2)
               target_language: <NoneType - at 0x10fa3ef98>
```

Still, this traceback is totally different from the @richardtc ones.

So: I did a release and I'll open a separate issue for plone.app.multilingual.

**Comment by keul** [comment]
@cekk also: shared on pypi
