### ISSUE TITLE
Translation for a Portlet Page ? 

### ISSUE THREAD

**Issue by webgeo** [collective/collective.portletpage#12]
Hello,

Hello,

Is it possible to have a translation for a 'Portlet Page' ?
My homepage is a 'Portlet Page'  and I would like to have this in a second language but I can't find the option.

Thank you,

**Comment by keul** [comment]
You need an add-on, and which ones depends on the version of Plone you are using.

LinguaPlone is the add-on normally used on Plone minor than version 5 (but it seem that Portlet Page is not supporting it right now).
If you are on Plone 4.3 or Plone 5 you need add-on plone.app.multilingual (shipped with Plone 5), plus the archetypes.multilingual extension.
But I fear there are issue with this and portlet page... See #11.

So... I really don't know if you can do this right now. Please reports here which version of Plone are you using.

**Comment by webgeo** [comment]
Hello, 

Thanks for your answer.
I am on Plone 4..3.2 with MultilanguagePlone 1.0.
I 've the translation tab's for my text pages but how do for the portlets?

Thanks,

**Comment by keul** [comment]
@webgeo sorry I don't understand what multilanguageplone is.

You mean [plone.app.multilingual](https://pypi.python.org/pypi/plone.app.multilingual)? If yes, have you installed also [archetypes.multilingual](https://pypi.python.org/pypi/archetypes.multilingual)?

**Comment by keul** [comment]
Never get feedback from @webgeo. Close
